# This is the main configuration file for the application.

# Configuration section about the server-logs settings.
logging:
  # Displays information to help debugging the application
  debug-mode: true

  # Displays information to help developers with verbose logs from the application
  dev-mode  : true

game-modes-path: "../../data/gamemodes"

seeds:
  - 4155519082845793722
  - 1449369639546214984
  - -6505837170832228537
  - 932475610972574098
  - -4705034784483231674
  - 5832038334522793048