# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8u_323
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
        
    - name: Restore local Maven repository cache
      id: cache-local-maven
      uses: actions/cache/restore@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-mavenlocal
        
    - name: Compile BuildTools 1.8.X
      if: steps.cache-local-maven.outputs.cache-hit != 'true'
      uses: SpraxDev/Action-SpigotMC@v4.2.0
      with: 
        versions: 1.8.8
        
    - name: Build & Test with Gradle for MC 1.8.X
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    
    - name: Save local Maven repository cache
      if: steps.cache-local-maven.outputs.cache-hit != 'true'
      id: save-local-maven
      uses: actions/cache/save@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-mavenlocal
